dist: xenial
language: generic
if: branch = master
git: { depth: 3 }
# arch:
#   # - amd64
#   - arm64
os: linux
services:
  - docker
env:
  global:
    - DOCKERHUB_USER="harvzor"
    - IMAGE_REPO_NAME="scrobbler-server"
script:
  - source ./multi-arch-docker-ci.sh
  - travis_wait 40 multi_arch_docker::main
deploy:
  - provider: script
    script:
      docker login -u $DOCKERHUB_USER -p $DOCKER_HUB_PASS && docker push $DOCKERHUB_USER/$IMAGE_REPO_NAME:latest && docker push $DOCKERHUB_USER/$IMAGE_REPO_NAME:$TRAVIS_BUILD_NUMBER 
    on:
      all_branches: true
    skip_cleanup: true
